### ISSUE TITLE
.min() is ambigous

### ISSUE THREAD

**Issue by pornel** [SergiusIW/noisy_float-rs#10]
Rust has added `.min()` to `Ord`, so now noisy_float's `.min` became unusable:

>   |                   ^^^ multiple `min` found
>    |
>    = note: candidate #1 is defined in an impl of the trait `std::cmp::Ord` for the type `types::noisy_float::NoisyFloat<_, _>`
>    = note: candidate #2 is defined in an impl of the trait `types::noisy_float::prelude::Float` for the type `types::noisy_float::NoisyFloat<_, _>`

**Comment by SergiusIW** [comment]
I see. The num_traits::Float trait is not in my control, so I can't change that. I think the best way to handle this is to add the min and max methods redundantly to the NoisyFloat implementation itself, which should resolve this issue. I just pushed a commit to master with this change.
