### ISSUE TITLE
Implement Hash?

### ISSUE THREAD

**Issue by FauxFaux** [SergiusIW/noisy_float-rs#13]
Is it safe to implement `Hash` on `R64`?

Many of the classic problems with implementing `Hash` are around the different ways a `NaN` and `Inf` can be stored in the bit representation, which shouldn't apply here?

Is it guaranteed that floats are in canonical representation while inside an R64?

If not, I'd be interested in documentation explaining that this isn't the case. :smile:

**Comment by SergiusIW** [comment]
Yes, all `NoisyFloat`s (e.g. `R64`) are required to be non-`NaN`. I don't see a reason not to implement `Hash` on `NoisyFloat`. Actually, `Inf` (plus or minus) only has a single bit representation in IEEE standards, unlike `NaN`. The only thing we would need to be careful about is the number zero, which has two different bit representations (`+0` and `-0`). But this could be taken into account when implementing the `hash` method. I will upload a commit for this shortly.
