### ISSUE TITLE
docs.rs Documentation Unavailable

### ISSUE THREAD

**Issue by jean-airoldie** [SergiusIW/noisy_float-rs#20]
As of Sunday, October 14, 2018, the [1.8.0 documentation](https://docs.rs/noisy_float/0.1.8/noisy_float/) is unavailable.

**Comment by LukeMathWalker** [comment]
Still true unfortunately. Any idea what might be the cause?

**Comment by SergiusIW** [comment]
There is a build failure log here https://docs.rs/crate/noisy_float/0.1.8/builds/118841 . It seems that whatever version of the compiler they were using at the time did not like the #[repr(transparent)] attribute. I suspect this may fix itself when a new version of noisy_float is published. In the meantime, the older docs are still accessible: https://docs.rs/crate/noisy_float/0.1.8

**Comment by SergiusIW** [comment]
Docs are back up after releasing version 0.1.9.
