### ISSUE TITLE
Better docs on how to convert to u64 / f64 types please.

### ISSUE THREAD

**Issue by gilescope** [SergiusIW/noisy_float-rs#23]
Better docs on how to convert _to_ u64 / f64 types please.

I can never find out how to do this and have to keep hunting through the code as it doesn't seem to be mentioned in many places.

Would be really useful,

Thanks!

(edit: for people wondering its to_u64 in the float_impl.rs)

**Comment by gilescope** [comment]
It would also be really cool if this just worked:

let x: f64 = r64(3.0).into();

**Comment by SergiusIW** [comment]
I suppose I could add it to the examples in the crate-level api docs.

Back in 2016 when I was first writing this, I tried to get the into method to work but wasn't able to do so. I had a stackoverlow post here: https://stackoverflow.com/questions/39186652/unable-to-implement-into-trait-for-a-generic-struct.

**Comment by Migi** [comment]
> It would also be really cool if this just worked:
> 
> let x: f64 = r64(3.0).into();

I wrote a PR that makes this work (#24) if the underlying Float type is either `f32` or `f64` (which most of the time, it is).
