### ISSUE TITLE
Incorrect implementation of `Eq` in release mode

### ISSUE THREAD

**Issue by tspiteri** [SergiusIW/noisy_float-rs#26]
The code below in release mode will trip the assertion.

```rust
use noisy_float::prelude::*;
fn assert_eq_self<T: Eq>(t: T) {
    assert!(&t == &t);
}
fn main() {
    assert_eq_self(r64(0. / 0.));
}
```

In contrast, primitives like `i32` that do not panic on overflow in release mode still stick to a very specific behaviour, for example `a + b` in release mode will be `a.wrapping_add(b)`, which is still a very defined and correct behaviour.

**Comment by SergiusIW** [comment]
I wouldn't say that using `a + b` wrapping around in release mode is correct behavior. It would be considered unchecked erroneous behavior. Also, the behavior you mentioned in your example test is still well-defined, albeit erroneous, like using `a.wrapping_add(b)` in release mode for addition. This is the whole point of the library, so I can't follow through with this issue unless you have a constructive suggestion.
