### ISSUE TITLE
make this crate `no_std`

### ISSUE THREAD

**Issue by Byter09** [SergiusIW/noisy_float-rs#28]
Hello,

I'm working on a generic range and range-set library and require examples of continuous types that implement `Ord`. Of course floats are only `PartialOrd`, but using an optional feature gate I could implement examples and tests using this crate. Sadly it does not have `#![no_std]`, even though all [`std::*` uses](https://github.com/SergiusIW/noisy_float-rs/search?q=std%3A%3A&unscoped_q=std%3A%3A) are also present in [`core`](https://doc.rust-lang.org/core/) and both dependencies are also `no_std`. So without looking too deep into the code, I highly suspect the crate can be made `no_std` compatible.

As I'm currently working on my crate, I hope it is understandable that I require the knowledge of maintainers to tell me if this is actually the case, so I don't make false assumptions.

If it turns out, that this crate actually uses std-specific code, I can also gate its use behind a flag in my crate, but I'd obviously prefer to only have a single `noisy_float` flag instead of an addtional `std` flag.

Thank you for taking the time to look into this!

**Comment by SergiusIW** [comment]
The request is reasonable, and I don't foresee any issues with forgoing std. I'll put up a commit with `#![no_std]` in a moment.

**Comment by mamins1376** [comment]
This crate still does not support `#![no_std]`, as `num-traits` dependency has it's default features (which includes `std`) enabled. In order to fix this, you should use `num-traits` in `Cargo.toml` like this:
```toml
num-traits = { version = "0.2", default-features = false }
```
