### ISSUE TITLE
Panics on invalid value when deserializing

### ISSUE THREAD

**Issue by Ten0** [SergiusIW/noisy_float-rs#33]
According to the code here:
https://github.com/SergiusIW/noisy_float-rs/blob/83c097921ecc7123a9135b7ef7d154913c33c3d9/src/lib.rs#L331-L336
The library panics when deserializing a float that doesn't pass the checks. It should probably instead return a deserialization failure.

**Comment by SergiusIW** [comment]
Sounds reasonable to me. Would you be happy the following behavior?

```Rust
impl<'de, F: Float + Deserialize<'de>, C: FloatChecker<F>> Deserialize<'de> for NoisyFloat<F, C> {
    fn deserialize<D: Deserializer<'de>>(de: D) -> Result<Self, D::Error> {
        let value = F::deserialize(de)?;
        Self::try_new(value).ok_or_else(|| D::Error::custom("invalid float"))
    }
}
```

**Comment by Ten0** [comment]
That seems great. 🙂 Wouldn't it be even easier to understand the error if it mentioned that it's an invalid *noisy* float or something along those lines though? (I'd have said "normal" but unfortunately I believe this already means something very specific in the context of floating point numbers.)
