### ISSUE TITLE
Way to make it noisy even in release

### ISSUE THREAD

**Issue by Ten0** [SergiusIW/noisy_float-rs#36]
I'd like to be able to make NaN/inf floats noisy even in release mode (quick interface for "please panic if these are NaN because this shouldn't happen as per how they are built, and otherwise let me use `.cmp`").

Questions:
 - Should this be implemented here or outside?
 - Should this be made by implementing new checkers or by a feature?
 - Do you have an idea of what would be a good naming for the checked-even-in-release type aliases?

Thanks,

**Comment by SergiusIW** [comment]
Yes, you can easily do this outside of the crate by implementing new checkers. I leave the naming up to you. E.g.:

```Rust
pub struct AlwaysNoisyChecker;

impl<F: Float> FloatChecker<F> for AlwaysNoisyChecker {
    #[inline]
    fn assert(value: F) {
        assert!(Self::check(value), "unexpected NaN or infinity");
    }

    #[inline]
    fn check(value: F) -> bool {
        value.is_finite()
    }
}

pub type A32 = NoisyFloat<f32, AlwaysNoisyChecker>;
pub type A64 = NoisyFloat<f64, AlwaysNoisyChecker>;
```

I would not add this implementation to the crate itself because I do not like how big of a performance hit it is in release mode.
